spring:
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: uwe
    password: uwe
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

